#!/usr/bin/env bash
# Generate Secrets.xcconfig + FrigyNative.xcodeproj for Codemagic native SwiftUI builds.
set -euo pipefail

ROOT="${CM_BUILD_DIR:-$(pwd)}"
NATIVE_DIR="$ROOT/ios-swiftui"
SECRETS="$NATIVE_DIR/Config/Secrets.xcconfig"

require_var() {
  local name="$1"
  local value="${!name:-}"
  if [ -z "$value" ] || [ "$value" = "undefined" ]; then
    echo "ERROR: Missing required environment variable: $name"
    exit 1
  fi
}

require_var VITE_SUPABASE_URL
require_var VITE_SUPABASE_PUBLISHABLE_KEY

# xcconfig treats // as comment — escape slashes in https:// URLs.
escape_xcconfig_url() {
  printf '%s' "$1" | sed 's|://|:/$()/|'
}

SUPABASE_URL_ESCAPED="$(escape_xcconfig_url "$VITE_SUPABASE_URL")"
APP_WEB_HOST="${VITE_APP_WEB_HOST:-app.frigy.app}"
OAUTH_SCHEME="${OAUTH_REDIRECT_SCHEME:-frigy}"
OAUTH_HOST="${OAUTH_CALLBACK_HOST:-callback}"

mkdir -p "$NATIVE_DIR/Config"
cat >"$SECRETS" <<EOF
// Generated by scripts/codemagic-prepare-native-ios.sh — do not commit.
SUPABASE_URL = ${SUPABASE_URL_ESCAPED}
SUPABASE_ANON_KEY = ${VITE_SUPABASE_PUBLISHABLE_KEY}
APP_WEB_HOST = ${APP_WEB_HOST}
OAUTH_REDIRECT_SCHEME = ${OAUTH_SCHEME}
OAUTH_CALLBACK_HOST = ${OAUTH_HOST}
EOF

echo "Wrote $SECRETS"

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Installing xcodegen..."
  brew install xcodegen
fi

cd "$NATIVE_DIR"
xcodegen generate
test -d FrigyNative.xcodeproj || (echo "ERROR: FrigyNative.xcodeproj not generated" && exit 1)
echo "Generated $NATIVE_DIR/FrigyNative.xcodeproj"
