#!/usr/bin/env bash
# Generate Secrets.xcconfig + FrigyNative.xcodeproj for Codemagic native SwiftUI builds.
set -euo pipefail

ROOT="${CM_BUILD_DIR:-$(pwd)}"
NATIVE_DIR="$ROOT/ios-swiftui"
SECRETS="$NATIVE_DIR/Config/Secrets.xcconfig"

require_var() {
  local name="$1"
  local value="${!name:-}"
  if [ -z "$value" ] || [ "$value" = "undefined" ]; then
    echo "ERROR: Missing required environment variable: $name"
    exit 1
  fi
}

require_var VITE_SUPABASE_URL
require_var VITE_SUPABASE_PUBLISHABLE_KEY

# xcconfig treats // as comment — escape slashes in https:// URLs.
escape_xcconfig_url() {
  printf '%s' "$1" | sed 's|://|:/$()/|'
}

SUPABASE_URL_ESCAPED="$(escape_xcconfig_url "$VITE_SUPABASE_URL")"
APP_WEB_HOST="${VITE_APP_WEB_HOST:-app.frigy.app}"
OAUTH_SCHEME="${OAUTH_REDIRECT_SCHEME:-frigy}"
OAUTH_HOST="${OAUTH_CALLBACK_HOST:-callback}"
# RevenueCat (optional — paywall falls back to default prices when unset).
# Accept either VITE_REVENUECAT_API_KEY_IOS or bare REVENUECAT_API_KEY (Codemagic group variable).
REVENUECAT_API_KEY="${VITE_REVENUECAT_API_KEY_IOS:-${REVENUECAT_API_KEY:-}}"
# Accept either VITE_REVENUECAT_ENTITLEMENT_ID or bare REVENUECAT_ENTITLEMENT_ID.
REVENUECAT_ENTITLEMENT="${VITE_REVENUECAT_ENTITLEMENT_ID:-${REVENUECAT_ENTITLEMENT_ID:-Frigy Pro}}"

mkdir -p "$NATIVE_DIR/Config"
cat >"$SECRETS" <<EOF
// Generated by scripts/codemagic-prepare-native-ios.sh — do not commit.
SUPABASE_URL = ${SUPABASE_URL_ESCAPED}
SUPABASE_ANON_KEY = ${VITE_SUPABASE_PUBLISHABLE_KEY}
APP_WEB_HOST = ${APP_WEB_HOST}
OAUTH_REDIRECT_SCHEME = ${OAUTH_SCHEME}
OAUTH_CALLBACK_HOST = ${OAUTH_HOST}
REVENUECAT_API_KEY = ${REVENUECAT_API_KEY}
REVENUECAT_ENTITLEMENT_ID = ${REVENUECAT_ENTITLEMENT}
EOF

echo "Wrote $SECRETS"

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Installing xcodegen..."
  brew install xcodegen
fi

cd "$NATIVE_DIR"
echo "Cleaning stale Xcode build artifacts before project generation..."
rm -rf FrigyNative.xcodeproj 2>/dev/null || true

# Patch CURRENT_PROJECT_VERSION in project.yml before XcodeGen reads it, so the
# generated project.pbxproj already has the correct CFBundleVersion. This is more
# reliable than sed-patching the generated pbxproj afterwards (XcodeGen can emit
# the key in varying formats that the post-generation sed may not match).
_build_floor="${IOS_BUILD_NUMBER:-1}"
_cm_num="${CM_BUILD_NUMBER:-0}"
if [ "$_cm_num" -gt "$_build_floor" ]; then
  _build_floor="$_cm_num"
fi
echo "Patching CURRENT_PROJECT_VERSION → $_build_floor in project.yml"
if [ "$(uname -s)" = "Darwin" ]; then
  sed -i '' "s/CURRENT_PROJECT_VERSION: [0-9]*/CURRENT_PROJECT_VERSION: ${_build_floor}/" "$NATIVE_DIR/project.yml"
else
  sed -i "s/CURRENT_PROJECT_VERSION: [0-9]*/CURRENT_PROJECT_VERSION: ${_build_floor}/" "$NATIVE_DIR/project.yml"
fi

echo "Generating FrigyNative.xcodeproj with XcodeGen..."
xcodegen generate
test -d FrigyNative.xcodeproj || (echo "ERROR: FrigyNative.xcodeproj not generated" && exit 1)
echo "Generated $NATIVE_DIR/FrigyNative.xcodeproj"
