// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SECURITY WARNING: JWT tokens are stored in localStorage which is vulnerable to XSS attacks.
// This is a known limitation of browser-based authentication. Mitigation strategies:
// 1. Implement strict Content Security Policy (CSP) headers
// 2. Sanitize all user inputs to prevent XSS
// 3. Use security headers: X-Frame-Options, X-Content-Type-Options, X-XSS-Protection
// 4. Consider implementing refresh token rotation
// 5. Use httpOnly cookies if backend infrastructure supports it (requires server-side changes)
// For production, consider implementing token refresh with server-side validation.

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('[Supabase] VITE_SUPABASE_URL is not set. Please configure your environment variables.');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY is not set. Please configure your environment variables.');
}

// Create client with validation
let supabase;

try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    throw new Error('Supabase configuration is missing. Check environment variables.');
  }
} catch (error) {
  console.error('[Supabase] Failed to initialize client:', error);
  // Create a placeholder that will show proper error messages
  supabase = null as any;
}

export { supabase };
