// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SECURITY WARNING: JWT tokens are stored in localStorage which is vulnerable to XSS attacks.
// This is a known limitation of browser-based authentication. Mitigation strategies:
// 1. Implement strict Content Security Policy (CSP) headers
// 2. Sanitize all user inputs to prevent XSS
// 3. Use security headers: X-Frame-Options, X-Content-Type-Options, X-XSS-Protection
// 4. Consider implementing refresh token rotation
// 5. Use httpOnly cookies if backend infrastructure supports it (requires server-side changes)
// For production, consider implementing token refresh with server-side validation.

// Validate environment variables
console.log('[Supabase] Initializing with URL:', SUPABASE_URL?.substring(0, 20), '...');
console.log('[Supabase] Key present:', !!SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_URL || SUPABASE_URL === 'undefined' || SUPABASE_URL === '') {
  console.error('[Supabase] VITE_SUPABASE_URL is missing or empty. Please set it in your Environment Variables (not Secrets) in Builder.io.');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'undefined' || SUPABASE_PUBLISHABLE_KEY === '') {
  console.error('[Supabase] VITE_SUPABASE_PUBLISHABLE_KEY is missing or empty. Please set it in your Environment Variables (not Secrets) in Builder.io.');
}

// Create client with validation
let supabase;

try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && SUPABASE_URL !== 'undefined' && SUPABASE_URL !== '' && SUPABASE_PUBLISHABLE_KEY !== 'undefined' && SUPABASE_PUBLISHABLE_KEY !== '') {
    supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    console.warn('[Supabase] Client initialization deferred - environment variables missing.');
    supabase = null as any;
  }
} catch (error) {
  console.error('[Supabase] Failed to initialize client:', error);
  supabase = null as any;
}

export { supabase };
